#! /bin/bash

# sysinfo_page - A script to produce an HTML file

#################################### 
	#Constants
####################################

TITLE="My System Info for $HOSTNAME"
RIGHT_NOW=$(date +"$x %r %Z")
TIME_STAMP="Updated on $RIGHT_NOW by $USER"

#################################### 
	#Main
####################################

cat <<- EOF 
	<html>
	<head>
		<title>
		$TITLE
		</title>
	</head>

	<body>
		<h1>$TITLE</h1>
		<p>$TIME_STAMP</p>
		<p>$(system_info)</p>
		<p>$(show_uptime)</p>
		<p>$(drive_space)</p>
		<p>$(home_space)</p>
	</body
	</html>
EOF